### ISSUE TITLE
Search crashes when result is extremely common

### ISSUE THREAD

**Issue by zeptonaut** [zeptonaut/shakesearch#7]
**How to reproduce**: Search for "or"

**Expected**: Lots of results are returned slowly.

**Actual**: The network request fails. Examining the go server logs turns up:

```
4:35:54 PM web.1 |  2023/02/13 16:35:54 http: panic serving 127.0.0.1:56513: runtime error: slice bounds out of range [-90:]
4:35:54 PM web.1 |  goroutine 65 [running]:
4:35:54 PM web.1 |  net/http.(*conn).serve.func1()
4:35:54 PM web.1 |  	/usr/local/Cellar/go/1.19.5/libexec/src/net/http/server.go:1850 +0xbf
4:35:54 PM web.1 |  panic({0x127c3a0, 0xc00001a2b8})
4:35:54 PM web.1 |  	/usr/local/Cellar/go/1.19.5/libexec/src/runtime/panic.go:890 +0x262
4:35:54 PM web.1 |  main.(*Searcher).Search(0xc000012078, {0xc0007021ae?, 0x1290c96?})
4:35:54 PM web.1 |  	/Users/charlie/github/shakesearch/main.go:79 +0x18e
4:35:54 PM web.1 |  main.handleSearch.func1({0x13090f0, 0xc0000f61c0}, 0x10a87b3?)
4:35:54 PM web.1 |  	/Users/charlie/github/shakesearch/main.go:51 +0x9b
4:35:54 PM web.1 |  net/http.HandlerFunc.ServeHTTP(0xc000069af0?, {0x13090f0?, 0xc0000f61c0?}, 0x0?)
4:35:54 PM web.1 |  	/usr/local/Cellar/go/1.19.5/libexec/src/net/http/server.go:2109 +0x2f
4:35:54 PM web.1 |  net/http.(*ServeMux).ServeHTTP(0xc0007021ac?, {0x13090f0, 0xc0000f61c0}, 0xc000110500)
4:35:54 PM web.1 |  	/usr/local/Cellar/go/1.19.5/libexec/src/net/http/server.go:2487 +0x149
4:35:54 PM web.1 |  net/http.serverHandler.ServeHTTP({0xc000790330?}, {0x13090f0, 0xc0000f61c0}, 0xc000110500)
4:35:54 PM web.1 |  	/usr/local/Cellar/go/1.19.5/libexec/src/net/http/server.go:2947 +0x30c
4:35:54 PM web.1 |  net/http.(*conn).serve(0xc000000aa0, {0x1309540, 0xc00009adb0})
4:35:54 PM web.1 |  	/usr/local/Cellar/go/1.19.5/libexec/src/net/http/server.go:1991 +0x607
4:35:54 PM web.1 |  created by net/http.(*Server).Serve
4:35:54 PM web.1 |  	/usr/local/Cellar/go/1.19.5/libexec/src/net/http/server.go:3102 +0x4db
```

**Comment by zeptonaut** [comment]
There are actually two problems here: 

1. When the backend returns an invalid result, the frontend shouldn't crash but should instead show some error about our servers having problems.
2. The server shouldn't have problems for this particular query.

I'll debug these separately.

**Comment by zeptonaut** [comment]
# Fixing it so that the frontend doesn't choke when the backend has problems
This one is actually pretty easy: we just need to catch any `fetch` errors that occur in the search loader and send them to the main search route for display. We can pretty trivially do this by wrapping the whole `loader` for that screen in a `try...catch`. If we catch an error, we send an `error` key to the route component that can be rendered.

Here's what that looks like in practice: I chose to use a pretty generic error message.

<img width="873" alt="image" src="https://user-images.githubusercontent.com/1407397/219534330-ed9ea489-da11-4ec1-84bf-579751cac79a.png">

**Comment by zeptonaut** [comment]
# Figure out why the backend is choking on this particular query
Alright, now onto solving the actual problem. There are very common queries (e.g. searching for ".") that yield the same problem.

The main goal here is to get a debugger attached at the point where the error is occurring.

Following these instructions (https://www.rookout.com/blog/golang-debugging-tutorial/#:~:text=To%20debug%20a%20program%2C%20execute,running%20process%20waiting%20for%20instructions.), first, I want to install `dlv` with

```
go install github.com/go-delve/delve/cmd/dlv@latest
```

After that, I can attach the debugger with:

```
PORT=5000 dlv attach main.go
```

(The `PORT=5000` is required to reproduce the same behavior as `heroku local`.)

The program starts and I can immediately continue (just like gdb) with `c`.

Unfortunately, when I make the triggering search from the frontend, the backend panics like normal without hitting any breakpoint.

It looks like the reason for this is that, because the panic is happening in the main event loop for the web server, it's a _recovered_ panic and not an unrecovered panic. That's fine: we can just set a breakpoint at the beginning of the offending function with `break main.go:76`, rerun the problematic query, and now the breakpoint is being hit.

I'll reprint the problematic code here just so that it's easily visible:

```go
func (s *Searcher) Search(query string) []string {
	idxs := s.SuffixArray.Lookup([]byte(query), -1)
	results := []string{}
	for _, idx := range idxs {
		results = append(results, s.CompleteWorks[idx-250:idx+250])
	}
	return results
}
```

Moving to the next line and printing `idxs` with `p idxs`, I get:

```
[]int len: 37952, cap: 37952, [4757897,4803806,2265680,4161853,4789590,2024530,4777313,3278099,3288264,3363759,3564667,3473100,3544775,3486679,3579083,3613926,3502025,3604963,3575469,3469056,3520612,3545943,3472453,3519219,3579535,3470662,3471277,3522767,3485552,2190421,2215386,2829418,4844697,1655081,2999554,4147514,2969144,1753377,3243708,3265288,3303207,4815302,4851449,5269159,2172588,4859758,2188949,2986428,2195725,667389,671608,2728764,2138540,1869155,526663,4803856,1896727,2389346,4144463,672074,4766888,2142087,2144713,4669394,...+37888 more]
```

Quickly looking at the return type of `Lookup` for a `SuffixArray` from the documentation:

> Lookup returns an unsorted list of at most n indices where the byte string s occurs in the indexed data. If n < 0, all occurrences are returned. The result is nil if s is empty, s is not found, or n == 0. Lookup time is O(log(N)*len(s) + len(result)) where N is the size of the indexed data.

In order to find the exact condition where we're failing, I'm going to set a conditional breakpoint for when `(idx - 250) < 0`.

I can do this with the combination of two commands: the first I've already executed `break main.go:79`. Now, I just need to add a condition to when that breakpoint is executed with 

```
cond 3 (idx - 250) < 0
```

I can confirm the conditional is attached with:

```
$ breakpoints
Breakpoint 3 (enabled) at 0x136c953 for main.(*Searcher).Search() ./main.go:79 (1)
	cond (idx - 250) < 0
```

Now, I just continue execution of the program with `c` and 🤞 that we hit the breakpoint.

... unfortunately, that doesn't work either. I'm not sure if the program is just running so slowly now in debug mode that it just can't make it through all of the occurrences of `or` in the texts.

# Back to print statements
Regardless, I can do just a regular, boring-ol:

```go
fmt.Println("Current idx: ", idx)
```

adding that on the line before the index error that we're hitting. That gives me:

```
10:12:16 PM web.1 |  Current idx:  1701595
10:12:16 PM web.1 |  Current idx:  2719931
10:12:16 PM web.1 |  Current idx:  2725063
10:12:16 PM web.1 |  Current idx:  2723612
10:12:16 PM web.1 |  Current idx:  5753451
10:12:16 PM web.1 |  Current idx:  109
```

which makes it immediately clear what the problem is. Taking the slice of `[idx-250:idx+250]` on the text is meant to supply additional context around the match. However, if the match happens to be at character 109, for example (where it is), then trying to give 250 characters of context _before_ the match will cause a slice out of bounds error.

We can fix this by just writing a quick `int` clamp function and making sure that we clamp the indices that we're using by the start and end of the text size:

```go
// Clamp restricts n to be between min and max, returning min if n 
// is less than min and max if n is more than min.
func Clamp(n, min, max int) int {
	if n < min {
		return min
	}
	if n > max {
		return max
	}
	return n
}

// ...

func (s *Searcher) Search(query string) []string {
	idxs := s.SuffixArray.Lookup([]byte(query), -1)
	results := []string{}
	for _, idx := range idxs {
		startIdx := Clamp(idx - 250, 0, len(s.CompleteWorks))
		endIdx := Clamp(idx + 250, 0, len(s.CompleteWorks))
		results = append(results, s.CompleteWorks[startIdx:endIdx])
	}
	return results
}
```

Rerunning the query here succeeds.
